version: '3.8'
services:
  vprodb:
    build:
      context: ./Docker-files/db
    image: vprocontainers/vprofiledb  # Moved image property outside the build block
    container_name: vprodb
    ports:
      - "3307:3306"
    volumes:
      - vprodbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=vprodbpass

  vprocache01:
    image: memcached
    ports:
      - "11211:11211"

  vpromq01:
    image: rabbitmq
    ports:
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  vproapp:
    build:
      context: ./Docker-files/app
    image: vprocontainers/vprofileapp  # Moved image property outside the build block
    container_name: vproapp
    ports:
      - "8081:8080"
    volumes:
      - vproappdata:/usr/local/tomcat/webapps

  vproweb:
    build:
      context: ./Docker-files/web
    image: vprocontainers/vprofileweb  # Moved image property outside the build block
    container_name: vproweb
    ports:
      - "3000:80"

volumes:
  vprodbdata: {}
  vproappdata: {}
